server:
  port: 8888

spring:
  application:
    name: GateWay
  cloud:
    gateway:
        routes:
          - id: User
            uri: lb://User
            predicates:
              - Path=/**
          - id: document
            uri: lb://Document
            predicates:
              - Path=/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
